<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_tes extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_tes_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('user_tes/user_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->User_tes_model->json();
    }

    public function read($id) 
    {
        $row = $this->User_tes_model->get_by_id($id);
        if ($row) {
            $data = array(
		'kd_dosen' => $row->kd_dosen,
		'password' => $row->password,
		'hak_akses' => $row->hak_akses,
	    );
            $this->load->view('user_tes/user_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('user_tes'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('user_tes/create_action'),
	    'kd_dosen' => set_value('kd_dosen'),
	    'password' => set_value('password'),
	    'hak_akses' => set_value('hak_akses'),
	);
        $this->load->view('user_tes/user_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'password' => $this->input->post('password',TRUE),
		'hak_akses' => $this->input->post('hak_akses',TRUE),
	    );

            $this->User_tes_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('user_tes'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->User_tes_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('user_tes/update_action'),
		'kd_dosen' => set_value('kd_dosen', $row->kd_dosen),
		'password' => set_value('password', $row->password),
		'hak_akses' => set_value('hak_akses', $row->hak_akses),
	    );
            $this->load->view('user_tes/user_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('user_tes'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kd_dosen', TRUE));
        } else {
            $data = array(
		'password' => $this->input->post('password',TRUE),
		'hak_akses' => $this->input->post('hak_akses',TRUE),
	    );

            $this->User_tes_model->update($this->input->post('kd_dosen', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('user_tes'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->User_tes_model->get_by_id($id);

        if ($row) {
            $this->User_tes_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('user_tes'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('user_tes'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('password', 'password', 'trim|required');
	$this->form_validation->set_rules('hak_akses', 'hak akses', 'trim|required');

	$this->form_validation->set_rules('kd_dosen', 'kd_dosen', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file User_tes.php */
/* Location: ./application/controllers/User_tes.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-28 04:32:29 */
/* http://harviacode.com */